# Big Mac Mega CSV
For this part we're going to be working with the *big_mac_source_data_v2.csv*, which is the original dataset. 

We'll be removing columns and removing rows to make the data more manageable and hone in on what we're looking for.

Please note that this compares the data by working with the US dollar at the time of publishing the dataset, not AUD. It's got the local price and dollar exchange.

For these activities please look at *08 - Removing and Splitting Dataframes* and onwards.

In [ ]:
import pandas as pd

#Read in the big_mac_source_data_v2.csv into a dataframe and show the first five rows of data (using .head())
df = pd.read_csv('data/big_mac_source_data_v2.csv')
df.head(5)

#Now, remove the iso_a3, GDP_dollar and GDP_local columns
df.drop(columns=['iso_a3', 'GDP_dollar', 'GDP_local'], inplace=True)

#Print the dataframe
df

               name currency_code  local_price    dollar_ex        date
0         Argentina           ARS         2.50      1.00000  2000-04-01
1         Australia           AUD         2.59      1.68000  2000-04-01
2            Brazil           BRL         2.95      1.79000  2000-04-01
3            Canada           CAD         2.85      1.47000  2000-04-01
4       Switzerland           CHF         5.90      1.70000  2000-04-01
...             ...           ...          ...          ...         ...
2083        Ukraine           UAH       105.00     36.93145  2023-07-01
2084        Uruguay           UYU       259.00     37.76500  2023-07-01
2085  United States           USD         5.58      1.00000  2023-07-01
2086        Vietnam           VND     74000.00  23687.50000  2023-07-01
2087   South Africa           ZAR        49.90     17.78375  2023-07-01

[2088 rows x 5 columns]

### Remove Rows
Now we want to remove some rows. We want to just focus on data from the start of the 2023-2024 financial year (01-07-2023).

There are two options for this:

#### Remove Rows by Index
We can remove all rows by index by looking at the index and deleting all rows. 

[Remove Rows By Index](https://scales.arabpsychology.com/stats/how-to-drop-rows-by-index-in-pandas-with-examples/#:~:text=Dropping%20rows%20by%20index%20in,provided%20to%20illustrate%20the%20process)

Look through the above to know how to drop rows by index. However, we need to know how to drop a broad range of rows by index. You'll need this code to find the index `df.loc[x:y].index`, which will go in place of `index=[...]` when calling the drop function.

#### Remove duplicates in a column
We can also remove all duplicates of a column except for the last value, which is probably a little easier. 


[Remove Duplicates and Keep the Latest](https://scales.arabpsychology.com/stats/how-do-i-drop-duplicate-rows-in-pandas-and-keep-the-latest-one/)

You'll want to remove the `sort_values('time')` section, but aside from that it should work if you remember to look at the `name` column as opposed to their example of `item` column. The only issue here is we do end up keeping a couple of countries which stopped reporting data (UAE and Russia). This means you will need to manually remove the first two rows (you can do this by index, look above).

In [18]:
#Remove the data using either method below. If you want to try both, COMMENT OUT ONE OF THEM AND CLEAR ALL OUTPUTS.
df = pd.read_csv('data/big_mac_source_data_v2.csv')
df = df.drop(index=df.iloc[0:1946,:].index)

df

,name,iso_a3,currency_code,local_price,dollar_ex,GDP_dollar,GDP_local,date
1946,United Arab Emirates,ARE,AED,18.00,3.67300,51305.686,1.884201e+05,2023-01-01
1947,Argentina,ARG,ARS,980.00,184.69875,13655.200,1.785087e+06,2023-01-01
1948,Australia,AUS,AUD,7.25,1.41854,65526.118,9.428825e+04,2023-01-01
1949,Austria,AUT,EUR,4.48,0.91950,52264.871,4.959295e+04,2023-01-01
1950,Azerbaijan,AZE,AZN,4.90,1.70250,6826.434,1.160494e+04,2023-01-01
...,...,...,...,...,...,...,...,...
2083,Ukraine,UKR,UAH,105.00,36.93145,4348.570,1.406445e+05,2023-07-01
2084,Uruguay,URY,UYU,259.00,37.76500,20221.940,8.324901e+05,2023-07-01
2085,United States,USA,USD,5.58,1.00000,76348.494,7.634849e+04,2023-07-01
2086,Vietnam,VNM,VND,74000.00,23687.50000,4086.519,9.564814e+07,2023-07-01
2087,South Africa,ZAF,ZAR,49.90,17.78375,6694.358,1.095364e+05,2023-07-01

## Create .csv File
Let's finish this off by storing just the 01-07-2023 values into a new .csv file.

In [21]:
#Write updated DataFrame to .csv file 'big_mac_2023.csv'
df.to_csv('data/big_mac_2023.csv',
          index=False)